#!/usr/bin/env bash

set -eu

book_name=$1

cd $(dirname $0)

work_dir=$(mktemp -d -t obp-extract-cit-XXXXXX)

cleanup () {
    local rv=$?
    rm -rf -- "$work_dir"
    exit $rv
}

trap cleanup EXIT

echo "Copy relevant files to work directory"
unzip -q ${book_name}.xml.zip -d $work_dir
cp ${book_name}.xml $work_dir/doi-deposit.xml

echo "Execute the stylesheet to extract citations"

(cd $work_dir; \
    saxonb-xslt -s:XML-edition/entire-book.xml \
                -xsl:Extract-citations-from-book.xsl -ext:on; \
    echo "Copy citations back")

cp -r $work_dir/DOI-citations/. .
