#!/usr/bin/env bash

set -e
cd "$(dirname $0)"

check () {
    if ! [ -x "$(command -v $1)" ]; then
	echo "Error: $1 is not installed." >&2
	exit 1
    fi
}

check "saxonb-xslt"

git submodule update --init
